spring:
  cloud:
    gateway:
      routes:
       - id : r1
         uri: http://localhost:8090/
         predicates:
            - Path=/appointments/**
            - Path=/consultations/**
       - id : r2
         uri: http://localhost:8091/
         predicates:
            - Path=/doctors/**
            - Path=/patients/**
  application:
    name: gateway-service
server:
  port: 8888

